[imu]
input_file = ./assets/activate_data.txt
sample_rate = 200.0  # IMU采样率（Hz）
need_trans = false  # 是否做坐标转换（右前上-> 前右下）
acc_noise = [1.25002800e-3, 1.25002800e-3, 1.25002800e-3]          # 加计白噪声（m/s/sqrt(s)）
gyro_noise = [3.53553391e-3, 3.53553391e-3, 3.53553391e-3]         # 陀螺仪白噪声（deg/sqrt(s)）
acc_random_walk = [5.62499778e-5, 5.62499778e-5, 5.62499778e-5]    # 加计随机游走（m/s^2/sqrt(s)）
gyro_random_walk = [2.71600196e-5, 2.71600196e-5, 2.71600196e-5]   # 陀螺仪随机游走（deg/s/sqrt(s)）

# 对准相关设置
[alignment]
start_search_length = 600.0  # 初始对准搜索时长（s）
end_search_length = 400.0   # 末端对准搜索时长（s）
min_static_duration = 180.0  # 静止最短时长（s）
start_align_acc_bias = [0.0, 0.0, 0.0]  # 初始对准加计零偏（m/s^2）
start_align_gyro_bias = [0, 0, 0]  # 初始对准陀螺仪零偏（rad/s）
# start_align_gyro_bias = [0.0013054298, -0.0009832855, -0.0000158156]
start_align_acc_bias = [0.0, 0.0, 0.0]  # 初始对准加计零偏（m/s^2）
end_align_acc_bias = [-0.0346125116,-0.1210524789,0.4151474924]
end_align_gyro_bias = [0.0012787765, -0.0009252009, 0.0001797996]

[gnss]
input_file = ./assets/gnss_20260602_110011_682828.pos
lever_arm = [0.1825, -0.186, -0.09]   # 杆臂（m）

[forward_lci]
output_file = ./assets/results/forward_lci_result.csv
gnss_time_tolerance = 0.001  # GNSS时间容差（s）
use_gnss_velocity = true    
use_zupt = false
use_nhc = false
corr_time = 3600.0
init_pos_std = [1.0, 1.0, 1.0]  # 初始位置标准差（m）
init_vel_std = [0.1, 0.1, 0.1]  # 初始速度标准差（m/s）
init_att_std_deg = [5.0, 5.0, 15]  # 初始姿态标准差（deg）
init_acc_bias_std = [0.025, 0.025, 0.025]  # 初始加计零偏标准差（m/s^2）
init_gyro_scale_std = [0.001, 0.001, 0.001]  # 初始陀螺仪比例因子标准差（无量纲）
init_acc_scale_std = [0.001, 0.001, 0.001]  # 初始加计比例因子标准差（无量纲）
zupt_std = [0.05, 0.05, 0.05]
zupt_acc_threshold = 0.15
zupt_gyro_threshold = 0.02
zupt_min_duration = 2
nhc_std = [0.0, 0.50, 0.50]

[backward_lci]
output_file = ./assets/results/backward_lci_result.csv

[fused_lci]
output_file = ./assets/results/fused_lci_result.csv

[realtime_stream]
protocol = udp
bind_host = 0.0.0.0
port = 9000
target_host = 127.0.0.1
target_port = 9000
tcp_backlog = 1
poll_timeout_ms = 200
max_packet_size = 4096
default_gps_week = 0

[realtime_forward_lci]
output_file = ./assets/results/realtime_forward_lci_result.csv
print_interval = 200
alignment_check_interval = 50

[realtime_file_sender]
imu_file = ./assets/activate_data.txt
gnss_file = ./assets/gnss_20260602_110011_682828.pos
speed = 1.0
loop = false
send_imu = true
send_gnss = true
startup_wait_ms = 1000
log_interval = 500
